#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb  7 09:02:13 2019

@author: felipe
"""
import warnings
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
from pylab import rcParams
import statsmodels.api as sm
import trendAnalysis as tr
import utilities as util
import locale
import seaborn as sns
locale.setlocale(locale.LC_TIME, "en_US.UTF-8") 

##Settings
warnings.filterwarnings("ignore")
plt.style.use('fivethirtyeight')

rcParams['figure.figsize'] = 18, 8

#setting plotting window parameters
matplotlib.rcParams['axes.labelsize'] = 14
matplotlib.rcParams['xtick.labelsize'] = 12
matplotlib.rcParams['ytick.labelsize'] = 12
matplotlib.rcParams['text.color'] = 'k'

ROOT_FOLDER  = '/home/felipe/Materias/TCC/'
#loading PLD data
MAIN_DIR = ROOT_FOLDER + '/PLD_Data/PLD_Outubro_2018'
MAIN_DIR += '/10_out18_RV0_logENA_Mer_d_preco_m_0/'
ONS_DIR = ROOT_FOLDER + 'PLD_Data/ONS_DATA'
mydateparser = lambda x: pd.datetime.strptime(x, "%m/%Y")
meanPLD = pd.read_csv(MAIN_DIR + 'PLD_medio.csv', \
                      parse_dates=['Mês'], sep="\\s+",\
                      date_parser=mydateparser)


PLOT_DIR = ROOT_FOLDER + '/PLD_Data/src/plots/SeriesTemporais/'
INITIAL_DATE = '01/2015'
mPLDSE = meanPLD[['Mês', 'SE/CO']]
mPLDSE.columns = ['month', 'price']
mPLDSE.set_index('month', inplace=True)
mPLDSE = mPLDSE.sort_index()
mPLDSE = mPLDSE.loc[mPLDSE.index >= INITIAL_DATE]

mPLDSE.index.inferred_freq

BEST_WINDOW_SIZE_MA = 16
T_SEASONAL = 12
plt.close('all')
SAVE_FIG = False
#Settings


def ReadONSEditedCSV(filename, columnName, dateParser=None):
    if dateParser is None:
        mydateparser = lambda x: pd.datetime.strptime(x, "%B %Y")
    else:
        mydateparser = dateParser   
    data = pd.read_csv(ONS_DIR + filename,\
                           parse_dates=['month'], \
                           date_parser=mydateparser)
    data.set_index('month', inplace=True)
    data.columns = [columnName]
    data = data.sort_index()
    data = data.loc[data.index < '20181001']
    return data
    

totalStoredEnergy = ReadONSEditedCSV('/Simples_Energia_Armazenada_Mês_data_editado.csv', 'Total Stored Energy')
uheStoredEnergy = ReadONSEditedCSV('/Simples_Geração_de_Energia_Barra_Mês_data_UHE_editado.csv', 'UHE Stored Energy')
unStoredEnergy = ReadONSEditedCSV('/Simples_Geração_de_Energia_Barra_Mês_data_UN_editado.csv', 'UN Stored Energy')
uteStoredEnergy = ReadONSEditedCSV('/Simples_Geração_de_Energia_Barra_Mês_data_UTE_editado.csv', 'UTE Stored Energy')
loadEnergy = ReadONSEditedCSV('/Simples_Carga_de_Energia_Barra_Mês_data_editado.csv', 'Load Energy')
ena = ReadONSEditedCSV('/Simples_Energia_Natural_Afluente_Subsistema_Barra__data_editado.csv', 'ENA')
mydateparser = lambda x: pd.datetime.strptime(x, "%Y-%m-%d")
afSum = ReadONSEditedCSV('/FStation.csv', 'Afluent Flow Sum', mydateparser)

cor = pd.concat([mPLDSE, totalStoredEnergy], axis=1)
cor = pd.concat([cor, uheStoredEnergy], axis=1)
cor = pd.concat([cor, uteStoredEnergy], axis=1)
cor = pd.concat([cor, loadEnergy], axis=1)
cor = pd.concat([cor, ena], axis=1)
cor = pd.concat([cor, afSum], axis=1)

ax = plt.axes()
correlation = cor.corr()
correlation.to_csv('corr_ons.csv')
sns.heatmap(correlation, xticklabels=correlation.columns, \
            yticklabels=correlation.columns, cmap='RdBu', ax=ax)
ax.set_title("Correlation between ONS DATA and PLD")
plt.show()
