#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb  4 09:43:45 2019

@author: felipe
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jan 13 20:15:10 2019

@author: felipe
"""

import warnings
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
from pylab import rcParams

##Settings
warnings.filterwarnings("ignore")
plt.style.use('fivethirtyeight')

rcParams['figure.figsize'] = 18, 8

#setting plotting window parameters
matplotlib.rcParams['axes.labelsize'] = 14
matplotlib.rcParams['xtick.labelsize'] = 12
matplotlib.rcParams['ytick.labelsize'] = 12
matplotlib.rcParams['text.color'] = 'k'

ROOT_FOLDER  = '/home/felipe/Materias/TCC/'
PLOT_FIG_NAME = "PLD_SE.jpg"
#loading PLD data
MAIN_DIR = ROOT_FOLDER + '/PLD_Data/PLD_Outubro_2018'
MAIN_DIR += '/10_out18_RV0_logENA_Mer_d_preco_m_0/'
PLOT_TITLE = 'PLD Subsistema SE/CO'

## Settings
mydateparser = lambda x: pd.datetime.strptime(x, "%m/%Y")
meanPLD = pd.read_csv(MAIN_DIR + 'PLD_medio.csv', \
                      parse_dates=['Mês'], sep="\\s+",\
                      date_parser=mydateparser)
mPLDSE = meanPLD[['Mês', 'SE/CO']]
mPLDSE.columns = ['Mês', 'Preço']
mPLDSE.set_index('Mês', inplace=True)
mPLDSE = mPLDSE.sort_index()
mPLDSE.plot(title=PLOT_TITLE, legend=True)
plt.ylabel('Preço')
plt.xlabel('Ano')
plt.savefig(PLOT_FIG_NAME, bbox_inches='tight')